# The path to the local model directory or Hugging Face repo.
model: "mlx-community/Mistral-Nemo-Instruct-2407-4bit"

# Whether or not to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "data/mistral-nemo-12b-data"

# The PRNG seed
seed: 3407

# Number of layers to fine-tune (32)
lora_layers: 16 # keep at 4

# Minibatch size. 4
batch_size: 4 # keep at 4

# Iterations to train for. Each epoch has 273 steps
iters: 1360  # keep number of iterations

# Number of validation batches, -1 uses the entire validation set.
val_batches: 50

# Adam learning rate.(1e-5) - 5e-6
learning_rate: 1e-5 # initial learning rate, not actually used if script is fixed

# Number of training steps between loss reporting.
steps_per_report: 10

# Number of training steps between validations.
steps_per_eval: 100 # keep validation frequency

# Load path to resume training with the given adapter weights.
resume_adapter_file: null

# Save/load path for the trained adapter weights.
adapter_path: "adapters/adapters_mistral-nemo-12b_3e_tuned_final"

# Save the model every N iterations.
save_every: 50

# Evaluate on the test set after training
test: false

# Number of test set batches, -1 uses the entire test set.
test_batches: -1

# Maximum sequence length.
max_seq_length: 2048

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true

# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  keys: ["self_attn.o_proj", "self_attn.k_proj", "self_attn.v_proj", "mlp.gate_proj", "mlp.up_proj", "mlp.down_proj", "self_attn.q_proj"]
  # These will be applied for the last lora_layers
  rank: 16
  alpha: 16
  scale: 4.0
  dropout: 0.1

# Schedule can only be specified in a config file, uncomment to use.
lr_schedule:
  name: cosine_decay
  warmup: 20 # 0 for no warmup
  warmup_init: 0 #1e-7  0 if not specified
  arguments: [1e-5, 1200, 1e-7] # passed to scheduler 0.0 last param should be like a linear decay