# The path to the local model directory or Hugging Face repo.
model: "microsoft/Phi-3.5-mini-instruct"
# Whether or not to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "data/phi3.5-2b-data"

# The PRNG seed
seed: 3407

num_layers: 4

# Minibatch size. 4
batch_size: 8

# Iterations to train for. Each epoch has 136.25 steps
iters: 274

# Number of validation batches, -1 uses the entire validation set.
val_batches: 50

# Adam learning rate.(1e-5) - 5e-6
learning_rate: 5e-5

# Number of training steps between loss reporting.
steps_per_report: 10

# Number of training steps between validations.
steps_per_eval: 25

# Load path to resume training with the given adapter weights.
resume_adapter_file: null

# Save/load path for the trained adapter weights.
adapter_path: "adapters/adapters_phi3.5-2b_3e"

# Save the model every N iterations.
save_every: 50

# Evaluate on the test set after training
test: false

# Number of test set batches, -1 uses the entire test set.
test_batches: 100

# Maximum sequence length.
max_seq_length: 2048

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true


# Schedule can only be specified in a config file, uncomment to use.
lr_schedule:
  name: cosine_decay
  warmup: 25                # ~10%
  warmup_init: 1e-7
  # arguments: [max_lr, decay_steps, end_lr]
  arguments: [5e-5, 274, 1e-7] # Aggiornato LR e decay_steps