# The path to the local model directory or Hugging Face repo.
model: "microsoft/Phi-3.5-mini-instruct"
# Whether or not to train (boolean)
train: true

# Directory with {train, valid, test}.jsonl files
data: "data/phi3.5-2b-a4-data"

# The PRNG seed
seed: 3407

# Number of layers to fine-tune (32)
lora_layers: 16 

# Minibatch size. 4
batch_size: 8

# Iterations to train for. Each epoch has 136.25 steps
iters: 408

# Number of validation batches, -1 uses the entire validation set.
val_batches: 50

# Adam learning rate.(1e-5) - 5e-6
learning_rate: 2e-4

# Number of training steps between loss reporting.
steps_per_report: 10

# Number of training steps between validations.
steps_per_eval: 100

# Load path to resume training with the given adapter weights.
resume_adapter_file: null

# Save/load path for the trained adapter weights.
adapter_path: "adapters/adapters_phi3.5-2b-a4_3e"

# Save the model every N iterations.
save_every: 137

# Evaluate on the test set after training
test: false

# Number of test set batches, -1 uses the entire test set.
test_batches: 100

# Maximum sequence length.
max_seq_length: 2048

# Use gradient checkpointing to reduce memory use.
grad_checkpoint: true

# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  keys: ["self_attn.o_proj", "self_attn.qkv_proj", "mlp.gate_up_proj", "mlp.down_proj"]
  # These will be applied for the last lora_layers
  rank: 16
  alpha: 16
  scale: 4.0
  dropout: 0.0

# Schedule can only be specified in a config file, uncomment to use.
lr_schedule:
  name: cosine_decay
  warmup: 5 # 0 for no warmup
  warmup_init: 0 #1e-7  0 if not specified
  arguments: [2e-4, 1200, 1e-7] # passed to scheduler 0.0 last param should be like a linear decay